name: Maven Deploy
on:
  push:
    branches:
      - master


#********************************************

#env:
  #USER_AZURE: jmartinezgi01@unal.edu.co
  #PASSWORD_AZURE: Azure1234


#********************************************

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven build
        run: mvn --file pom.xml package

#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Deploy to Github Package Registry
        env:
          USSER_GHITHUB: ${{ secrets.USER_GIT}}
          PASSWORD_GITHUB: ${{ secrets.TOKEN }}
        #run: mvn --settings settings.xml --file pom.xml deploy
        run: mvn --batch-mode --update-snapshots package
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: test java
        uses: actions/setup-java@v1
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Test
        run: mvn --batch-mode test
  
  
        
  Docker:
    name: push Docker image
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Ckeck out repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_DOCKER }}
          password: ${{ secrets.PASSWORD_DOCKER }}

      - name: Build and push
        run: docker build -t juandiaz9102/image-nginx:tag .

      - run: docker push juandiaz9102/image-nginx:tag



  build-and-deploy:
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      packages: write
      contents: read
    steps:
      - uses: azure/login@v1
        with:
          USER_AZURE: ${{ secrets.USER_AZURE }}
          PASSWORD_AZURE: ${{ secrets.PASSWORD_AZURE }}
      # login azure

      - run: az login -u ${{ secrets.USER_AZURE }} -p ${{ secrets.PASSWORD_AZURE }}    



      

      # bajar la imagen de docker hub
      
      #- run: docker pull nginx

      #entrar al cluster

      #- run: 

      # Deploy azure

      #- run: docker
          
          


#az webapp list --query "[?state=='Running']"