name: Maven Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Maven build
        run: mvn --file pom.xml package

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: test java
        uses: actions/setup-java@v1
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Test
        run: mvn --batch-mode test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Deploy to Github Package Registry
        env:
          USSER_GHITHUB: ${{ secrets.USSER_GIT }}
          PASSWORD_GITHUB: ${{ secrets.TOKEN }}
        #run: mvn --settings settings.xml --file pom.xml deploy
        run: mvn --batch-mode --update-snapshots package

  Docker:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    needs: [deploy]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_DOCKER }}
          password: ${{ secrets.PASSWORD_DOCKER }}

      - name: Build and push Docker images
        #uses: docker/build-push-action@v3

        run: docker run -d --name nginx nginx:alpine
        


  



    #runs-on: ubuntu-latest
    #steps:
      #- name: checke
      #  uses: actions/checkout@v1

      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v2

     # - name: Set up Docker Buildx
      #  uses: docker/setup-buildx-action@v2

     # - name: Deploy to Docker_hub Package Registry
      #  uses: docker/login-action@v2
     #   with:
     #     USSER_DOCKER_HUB: ${{ secrets.USSER_DOCKER_HUB }}
     #     PASSWORD_DOCKER_HUB: ${{ secrets.PASSWORD_DOCKER_HUB }}

     # - name: Docker build and push
      #  uses: docker/build-push-action@v2
     #   with:
     #     context: .
     #     push: true
     #     tags: juandiaz9102/app-hello:helo-v1
