name: Maven Deploy
on:
  push:
    branches:
      - master
      
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: test java
        uses: actions/setup-java@v1
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Test
        run: mvn --batch-mode test
  
  publish-artifact:
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set up Maven Settings for deploy
        uses: s4u/maven-settings-action@v2.1.1
      - name: Publish package
        env:
          GITHUB_USERNAME: ${{ secrets.USER_GIT }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}        
        run: mvn source:jar deploy -DuniqueVersion=false -Dmaven.source.useDefaultManifestFile=true -Dmaven.source.includePom=true -DaltDeploymentRepository='github::default::https://maven.pkg.github.com/juandiaz9102/image-nginex'
        
  Docker:
    name: push Docker image
    runs-on: ubuntu-latest
    needs: [publish-artifact]
    permissions:
      packages: write
      contents: read
    steps:
      - name: Ckeck out repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USER_DOCKER }}
          password: ${{ secrets.PASSWORD_DOCKER }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: juandiaz9102/app:latest





    #name: push Docker image
    #runs-on: ubuntu-latest
    #needs: [deploy]
    #permissions:
      #packages: write
      #contents: read
    #steps:

      #- name: Ckeck out repo
       # uses: actions/checkout@v3

      #- name: Log in to Docker Hub
       # uses: docker/login-action@v2
       # with:
        #  username: ${{ secrets.USER_DOCKER }}
        #  password: ${{ secrets.PASSWORD_DOCKER }}

      #- name: Build and push
  
        #uses: docker/build-push-action@v3
       # with:
          #context: ./Dockerfile
          #push: true
          #tags: juandiaz9102/app:latest



        #run: docker run -d -t --name nginx nginx:alpine


        #run: docker build --tag go:test1 ./Dockerfile
      #- run: docker push go:tes1

      #- name: Build and push
        #uses: docker/build-push-action@v3
        #with:
          #context: .
          #push: true
          #tags: juandiaz9102/go:tes1
      
